/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x19, 0x9E, 0x5F, 0x25, 0x80, 0xE1, 0xD3, 0xE8}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 1 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }

#define VIAL_DEFAULT_PERMISSIVE_HOLD
#define VIAL_DEFAULT_IGNORE_MOD_TAP_INTERRUPT
// #define VIAL_DEFAULT_RETRO_TAPPING